### ISSUE TITLE
스터디 회고

### ISSUE THREAD

**Issue by jongmin92** [quick-starters/blockchain#4]

**Comment by evan-hwang** [comment]
Keep
- 혼자보면 읽기 힘들 수 있는 아예 모르는 분야 책에 대해서 같이 읽을 수 있어서 좋았다.
- 핵심 부분을 정리해놓아, 다시 복습하기 좋아보임

Problem
- 실습이 없는 책이다보니, 약간 루즈했다.
- 블록체인 첫 학습 책이다보니, 책 외적으로 더 파생공부하지는 못했다.

Try
- 실습이 조금이라도 있는 책을 선정하는 것도 지루함을 개선하기 좋겠다.

**Comment by jongmin92** [comment]
- Keep
  - 책의 내용이 어렵지 않아서 계획대로 잘 마무리됐다.
  - 서로 미리 책을 읽어오는 것이 좋았다.
  - 간단하게 정리한 것이 나중에 다시 읽어보기 좋았다.
  - 흥미 있는 주제로 진행하니 재밌었다.
- Problem
  - 실습(코딩)을 할 수 있는 부분이 없었다.
  - 인원이 줄어드니(3명->2명) 더 많은 의견 나누기가 어려웠다.
- Try
  - 실습도 같이 해보자.
